name: CD Deploy
'on':
  workflow_run:
    workflows:
    - CI Build
    types:
    - completed
    branches:
    - main
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name
      == 'workflow_dispatch' }}
    uses: ./.github/workflows/cd-deploy-reusable.yml
    with:
      image_tag: ${{ github.event.workflow_run.head_sha || github.sha }}
      service_name: ${{ github.event.repository.name }}
      health_check_url: ${{ vars.HEALTH_CHECK_URL }}
    secrets: inherit
